### ISSUE TITLE
requirement installation failed

### ISSUE THREAD

**Issue by shitl0ad** [lightbulb-framework/lightbulb-framework#2]
+--------------------------+--------+
| Name                     | Status |
+--------------------------+--------+
| six                      | OK     |
| stevedore                | OK     |
| pbr                      | OK     |
| cmd2                     | FAIL   |
| unicodecsv               | FAIL   |
| yaml                     | OK     |
| prettytable              | FAIL   |
| cliff                    | OK     |
| multiprocessing          | OK     |
| FAdo                     | OK     |
| dateutil                 | FAIL   |
| symautomata              | OK     |
| sfalearn                 | OK     |
| MySQLdb                  | OK     |
| OpenFST Python Extension | OK     |
+--------------------------+--------+

first, I install under my username (not sudo) failed, then I tried install under the sudo, it's also failed.
I tried install standalone by wget, then manual installation, few requirement was detect with OK, some not detect and it's also failed, do you know how to solve?

I am using ubuntu 16.04 (32bit)

**Comment by Murthysagi** [comment]
+1

**Comment by Narasimha1337** [comment]
Just install synaptic package manager : if you are using ubuntu just try this command 

> $ sudo apt-get install synaptic 

Search your module and then install it 👍

**Comment by shitl0ad** [comment]
Nice, it's working, I should closed the issue now.

thanks murthy.

**Comment by lianfeng30** [comment]
error

Makefile:443: recipe for target 'fst.lo' failed
make[2]: *** [fst.lo] Error 1
make[2]: Leaving directory '/lightbulb-framework-Tools-for-auditing-WAFS/openfst-1.5.4/src/lib'
Makefile:358: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/lightbulb-framework-Tools-for-auditing-WAFS/openfst-1.5.4/src'
Makefile:414: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
Requirements Status:

+--------------------------+--------+
| Name                     | Status |
+--------------------------+--------+
| six                      | OK     |
| stevedore                | OK     |
| pbr                      | OK     |
| cmd2                     | FAIL   |
| unicodecsv               | OK     |
| yaml                     | OK     |
| prettytable              | OK     |
| cliff                    | OK     |
| multiprocessing          | OK     |
| FAdo                     | OK     |
| dateutil                 | OK     |
| symautomata              | OK     |
| sfalearn                 | OK     |
| MySQLdb                  | OK     |
| OpenFST Python Extension | FAIL   |
+--------------------------+--------+

**Comment by lianfeng30** [comment]
im kali
