### ISSUE TITLE
some mistake 

### ISSUE THREAD

**Issue by lupus721** [lightbulb-framework/lightbulb-framework#5]
after lightbulb status it will notice 

`sudo apt-get install libmysqlclient-dev
sudo: apt-get: command not found
`
my system is centos 7

**Comment by istais** [comment]
Thanks for opening the issue.
In centos the command is  "sudo yum install <packagename>" instead of "sudo apt-get install <packagename>"
So finally it would be sudo yum install libmysqlclient-dev 
I will try to push a fix at the end of the day

**Comment by istais** [comment]
Fixed in the 0.14 version

sudo yum install -y mysql-devel
sudo yum install -y MySQL-python
